const sample = [
  {
    user_id: 123,
    user_name: 'Arjun',
    user_email: 'arjun@gmail.com',
    checkbooks: [
      {
        checkbook_name: 'Wells Fargo ...7963',
        checkbook_id: 10,
        totalOutstanding: 0,
        checks: [
          {
            check_id: 123,
            checkbook_id: 10,
            check_number: 5678,
            check_amount: 234.67,
            check_to: 'Pepsi Co',
            check_date: 'March 29, 2018',
            check_added_by: 123,
            check_cleared: false,
          },
          {
            check_id: 214,
            checkbook_id: 10,
            check_number: 5679,
            check_amount: 1789.23,
            check_to: '7up Bottling co',
            check_date: 'March 22, 2018',
            check_added_by: 123,
            check_cleared: false,
          },
          {
            check_id: 235,
            checkbook_id: 10,
            check_number: 5680,
            check_amount: 8976.53,
            check_to: 'Southern Wines',
            check_date: 'March 26, 2018',
            check_added_by: 123,
            check_cleared: false,
          },
          {
            check_id: 226,
            checkbook_id: 10,
            check_number: 5681,
            check_amount: 12304.67,
            check_to: 'Landlord Inc',
            check_date: 'March 29, 2018',
            check_added_by: 123,
            check_cleared: false,
          },
        ],
      },
      {
        checkbook_name: 'Wells Fargo ...2393',
        checkbook_id: 11,
        totalOutstanding: 0,
        checks: [
          {
            check_id: 123,
            checkbook_id: 10,
            check_number: 2345,
            check_amount: 2134.67,
            check_to: 'Pepsi Co',
            check_date: 'March 29, 2018',
            check_added_by: 123,
            check_cleared: false,
          },
          {
            check_id: 214,
            checkbook_id: 10,
            check_number: 2348,
            check_amount: 3789.23,
            check_to: '7up Bottling co',
            check_date: 'March 22, 2018',
            check_added_by: 123,
            check_cleared: false,
          },
          {
            check_id: 235,
            checkbook_id: 10,
            check_number: 2987,
            check_amount: 976.53,
            check_to: 'Southern Wines',
            check_date: 'March 26, 2018',
            check_added_by: 123,
            check_cleared: false,
          },
          {
            check_id: 226,
            checkbook_id: 10,
            check_number: 2988,
            check_amount: 1233.67,
            check_to: 'Landlord Inc',
            check_date: 'March 29, 2018',
            check_added_by: 123,
            check_cleared: false,
          },
        ],
      },
    ],
  },
];

export default sample;
